package com.example.lotterysystemproject.views.entrant;

import androidx.appcompat.app.AppCompatActivity;


/**
 * Represents the "QR" screen for entrants in the Lottery System Application.
 * Will allow entrants to access a QR scanning screen that will take them to the
 * respective events that generated by scanning the code.
 * Implementation is currently pending and serves as a placeholder.
 */
public class EntrantQRActivity extends AppCompatActivity {
}
