name: User Story
description: Create a new user story for the product backlog
title: "[US XX.XX.XX] - <Brief Title>"
labels: ["user-story", "backlog"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template
        Fill out the sections below to create a well-defined user story for the backlog.

  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: Unique identifier for this user story (e.g., US 01.01.01)
      placeholder: "US XX.XX.XX"
    validations:
      required: true

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      description: Estimate the effort/complexity using Fibonacci sequence
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "21"
        - "To be estimated"
    validations:
      required: true

  - type: dropdown
    id: risk_level
    attributes:
      label: Risk Level
      description: Assess the technical and requirement risk
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: sprint_release
    attributes:
      label: Sprint/Release
      description: Which sprint or release is this targeted for?
      options:
        - Sprint 1 - Half-way Checkpoint
        - Sprint 2 - Final Release
        - Future/Backlog
        - To be determined
    validations:
      required: true

  - type: input
    id: user_role
    attributes:
      label: User Role
      description: Who is this story for?
      placeholder: "e.g., entrant, organizer, admin"
    validations:
      required: true

  - type: textarea
    id: user_action
    attributes:
      label: User Action
      description: What does the user want to do?
      placeholder: "I want to..."
    validations:
      required: true

  - type: textarea
    id: user_benefit
    attributes:
      label: User Benefit
      description: Why does the user want this? What value does it provide?
      placeholder: "So that..."
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Any technical considerations, implementation details, or constraints
      placeholder: |
        - Implementation approach
        - Technology stack considerations
        - Performance requirements
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List related stories or external dependencies
      placeholder: |
        - US XX.XX.XX - <Related story>
        - External API or service dependencies
    validations:
      required: false

  - type: input
    id: ui_mockups
    attributes:
      label: UI/UX Mockups
      description: Link to design files, wireframes, or mockups
      placeholder: "https://figma.com/..."
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information, questions, or concerns
    validations:
      required: false
